### ISSUE TITLE
Dataset used

### ISSUE THREAD

**Issue by theostoican** [EmreTaha/Social-LSTM-VehicleTrajectory#1]
Hi, 

Could you please mention what dataset you've used both for training and testing?

Thank you.

**Comment by EmreTaha** [comment]
Hi,
The source of the data set was from the aachen university. But unfortunately the webpage is no longer there ( I don't know what happened), so I couldn't provide more information other than the normalized version of the dataset :(

**Comment by theostoican** [comment]
I understand. Thank you very much for your response :).

**Comment by RebornHugo** [comment]
> Hi,
> The source of the data set was from the aachen university. But unfortunately the webpage is no longer there ( I don't know what happened), so I couldn't provide more information other than the normalized version of the dataset :(


Thank you!
Is this dataset you used in your project?
[The Highway Drone Dataset](https://www.highd-dataset.com/)

**Comment by huling121** [comment]
> Hi,
> The source of the data set was from the aachen university. But unfortunately the webpage is no longer there ( I don't know what happened), so I couldn't provide more information other than the normalized version of the dataset :(
Can you tell me, what model is lost in data operation?Is the normalized operation?

**Comment by EmreTaha** [comment]
> Thank you!
> Is this dataset you used in your project?
> [The Highway Drone Dataset](https://www.highd-dataset.com/)

It looks similar, but I can't confirm whether they are same or not.



> > Can you tell me, what model is lost in data operation?Is the normalized operation?

No model is lost. I only normalized it between 0 and 1. The link to the data is not valid anymore.
