### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by AIwuya** [EmreTaha/Social-LSTM-VehicleTrajectory#5]
hi, the dataset in your code is NGSIM dataset ?

**Comment by Amyxi18** [comment]
hi, the dataset in your code is NGSIM dataset ?

**Comment by Amyxi18** [comment]
hi~,Why the GPU utilization is 0？Can the batch_size be modified?Why does it report an error if it is modified to another number，like 128、256.Looking forward to your reply！

**Comment by chenqq1** [comment]
> hi~,Why the GPU utilization is 0？Can the batch_size be modified?Why does it report an error if it is modified to another number，like 128、256.Looking forward to your reply！



> hi~，为什么GPU利用率为0？batch_size可以修改吗？为什么修改为另一个数字会数据集吗，可以交流报告错误，例如128、256.期待您的回复！

请问你解决了吗？这里用的是NGSIM数据集吗，可以交流一下吗

**Comment by EmreTaha** [comment]
Please see #4
